export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_PERNIL_START = 'PURCHASE_PERNIL_START';
export const PURCHASE_PERNIL = 'PURCHASE_PERNIL';
export const PURCHASE_PERNIL_SUCCESS = 'PURCHASE_PERNIL_SUCCESS';
export const PURCHASE_PERNIL_FAIL = 'PURCHASE_PERNIL_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';